#define CALL_FSTAT 0
#define CALL_LSTAT 1
#define CALL_STAT 2

#define SCRATCHPAD 0x10000
#define SCRATCHPAD_SIZE 2048

void call_exit (message *m);
void call_fork (message *m);
void call_read (message *m);
void call_write (message *m);
void call_open (message *m);
void call_close (message *m);
void call_wait (message *m);
void call_creat (message *m);
void call_link (message *m);
void call_unlink (message *m);
void call_waitpid (message *m, int mode);
void call_chdir (message *m);
void call_time (message *m);
void call_mknod (message *m);
void call_chmod (message *m);
void call_chown (message *m);
void call_brk (message *m);
void call_stat (message *m, int mode);
void call_lseek (message *m);
void call_getpid (message *m);
void call_mount (message *m);
void call_umount (message *m);
void call_setuid (message *m);
void call_getuid (message *m);
void call_stime (message *m);
void call_ptrace (message *m);
void call_alarm (message *m);
//void call_fstat (message *m);
void call_pause (message *m);
void call_utime (message *m);
void call_access (message *m);
void call_sync (message *m);
void call_kill (message *m);
void call_rename (message *m);
void call_mkdir (message *m);
void call_rmdir (message *m);
void call_dup (message *m);
void call_pipe (message *m);
void call_times (message *m);
void call_symlink (message *m);
void call_setgid (message *m);
void call_getgid (message *m);
void call_signal (message *m);
void call_rdlnk (message *m);
//void call_lstat (message *m);
void call_ioctl (message *m);
void call_fcntl (message *m);
void call_fs_ready (message *m);
void call_exec (message *m);
void call_umask (message *m);
void call_chroot (message *m);
void call_setsid (message *m);
void call_getpgrp (message *m);
void call_sigaction (message *m);
void call_sigsuspend (message *m);
void call_sigpending (message *m);
void call_sigprocmask (message *m);
void call_sigreturn (message *m);
void call_reboot (message *m);
void call_svrctl (message *m);
void call_sysuname (message *m);
void call_getsysinfo (message *m);
void call_getdents (message *m);
void call_llseek (message *m);
void call_fstatfs (message *m);
void call_select (message *m);
void call_fchdir (message *m);
void call_fsync (message *m);
void call_getpriority (message *m);
void call_setpriority (message *m);
void call_gettimeofday (message *m);
void call_seteuid (message *m);
void call_setegid (message *m);
void call_truncate (message *m);
void call_ftruncate (message *m);
void call_fchmod (message *m);
void call_fchown (message *m);
void call_getsysinfo_up (message *m);
void call_sprof (message *m);
void call_cprof (message *m);
void call_munmap (message *m);
void call_munmap_text (message *m);
